spring.application.name=AutomatedGstInvoiceChecker
spring.datasource.url=jdbc:h2:mem:company
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql= true

sandbox.api.base-url= https://api.sandbox.co.in
sandbox.api.gstin-url= /gst/compliance/public/gstin/search
sandbox.api.api-key= key_live_b14b9f23d895428b9b0f94f04939aec9
sandbox.api.token= eyJ0eXAiOiJKV1MiLCJhbGciOiJSU0FTU0FfUFNTX1NIQV81MTIiLCJraWQiOiIwYzYwMGUzMS01MDAwLTRkYTItYjM3YS01ODdkYTA0ZTk4NTEifQ.eyJ3b3Jrc3BhY2VfaWQiOiI3MWY0MzZhZC00ZDA4LTQ0Y2YtODIwZS0xNGYxNjBlYzBlNTYiLCJzdWIiOiJrZXlfbGl2ZV9iMTRiOWYyM2Q4OTU0MjhiOWIwZjk0ZjA0OTM5YWVjOSIsImFwaV9rZXkiOiJrZXlfbGl2ZV9iMTRiOWYyM2Q4OTU0MjhiOWIwZjk0ZjA0OTM5YWVjOSIsImF1ZCI6IkFQSSIsImludGVudCI6IkFDQ0VTU19UT0tFTiIsImlzcyI6InByb2QxLWFwaS5zYW5kYm94LmNvLmluIiwiaWF0IjoxNzc0MzUxNjQ5LCJleHAiOjE3NzQ0MzgwNDl9.oV2dZVPQNh0xM1MXvLXRn5JR3oJjsx_Bz-NuVy2BrhfuQDulQgzBB2VMPdu8mCxejpvL3avy3HHV6iMlIU3UbYCphQhD6VxIa06vDJO7uJr6jNUhmAxE5I1np3W8M1fGJYqmIryM9iPXXAIZQBU61veOL6JfGKgXSVHyIyfg1hqAsxjgupCvFWkB94Z8-_GJkpRFFBPNkHG5X3mJNPWieWErSQ1IUC5R7n9rMycZ3ZGvD4GnwD15KHFkONhiJnX5to4TzLhqMyyAfwjHCf73i0PaWkbGC6XNTndl87_IAhiJfveM2CbIOXbBy73uP_IOKAl6IUDw-ENkMv76lbKUmA